name: Deply to Production
on:
  push:
    branches:
      - main
jobs:
  build_and_install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: yarn install and build
        run: |
          yarn install
          yarn build
      - name: Archive compiled artifacts
        uses: actions/upload-artifact@v3
        with:
          name: distribution_folder
          path: dist

  deploy_to_publilshed_theme:
    runs-on: ubuntu-latest
    needs: build_and_install
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v3
        with:
          path: dist
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: '.'

      - uses: discolabs/deploy-shopify-theme-action@v1
        with:
          store: ${{ secrets.SHOP_STORE }}
          password: ${{ secrets.SHOP_ACCESS_TOKEN }}
          theme_id: ${{ secrets.PUBLISHED_SHOP_THEME_ID }}
          path: './dist/distribution_folder'
          additional_args: '--allow-live'
#           additional_args: '--ignored-file=config/settings_data.json'
